name: attha_nissaya
description:  Atthakatha Translation

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.2.0+3

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  flutter_riverpod: ^2.3.7
  vs_scrollbar: ^0.2.0
  shared_preferences: ^2.0.5
  enum_to_string: ^2.0.1
  flutter_markdown: ^0.6.1
  grouped_list: ^5.1.2
  scrollable_positioned_list: ^0.3.8
  path_provider: ^2.0.8
  path: ^1.8.0
  logger: ^2.0.2+1
  cupertino_icons: ^1.0.2
  flutter_widget_from_html_core: ^0.14.11
  sqflite: ^2.1.0
  sqflite_common_ffi: ^2.1.1+1
  sqlite3_flutter_libs:
  asset_pdf_viewer:
    # path: packages/asset_pdf_viewer_mobile
    path: packages/asset_pdf_viewer_desktop
  # app_links: ^3.2.0
  # url_protocol: ^1.0.0
  uni_links_desktop: ^0.1.3
  uni_links: ^0.5.1
  easy_debounce: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  json_serializable: ^6.1.4
  freezed: ^2.4.1
  build_runner:
  # flutter_launcher_icons: ^0.9.0
  icons_launcher: ^2.0.6
  msix: ^3.6.2

flutter_icons:
  android: false
  ios: false
  macos: false
  windows: true
  image_path: "assets/icon/attha_icon.png"

msix_config:
  display_name: Attha Nissaya
  identity_name: 38337PnDaza.AtthaNissaya
  publisher_display_name: PnDaza
  publisher: CN=D6488D0D-2C1E-4BF6-9E71-85196599EEB3
  msix_version: 1.1.0.0
  protocol_activation: atthanissaya
  store: true
  logo_path: .\assets\icon\attha_icon.png

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/database/attha_nsy.db
    - assets/books/cover/
    - assets/books/pdf/
    - assets/info.html

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700